"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "../../../components/ui/card"
import { Button } from "../../../components/ui/button"
import { Badge } from "../../../components/ui/badge"
import { Input } from "../../../components/ui/input"
import { Label } from "../../../components/ui/label"
import { Textarea } from "../../../components/ui/textarea"
import { Switch } from "../../../components/ui/switch"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../../../components/ui/select"
import {
  ImageIcon,
  FileText,
  Tag,
  Film,
  Upload,
  Clock,
  Globe,
  Lock,
  Users,
  Sparkles,
  X,
  Check,
  AlertCircle
} from "lucide-react"
import { useSearchParams } from "react-router-dom"

const autoGeneratedTags = [
  "게임 트렌드",
  "2026 게임",
  "AI 게임",
  "클라우드 게이밍",
  "게임 산업",
  "게임 전망",
  "메타버스 게임",
  "차세대 게임",
]

export function UploadForm() {
  const [searchParams] = useSearchParams()
  const topic = searchParams.get("topic") || "2026 게임 트렌드 예측"

  const [title, setTitle] = useState(topic)
  const [description, setDescription] = useState(
    `2026년 게임 업계를 뒤흔들 트렌드를 분석했습니다.\n\nAI 기술, 클라우드 게이밍, 메타버스까지 올해 주목해야 할 게임 트렌드를 모두 정리했습니다.\n\n⏰ 타임스탬프\n00:00 인트로\n01:23 AI 생성 콘텐츠\n05:45 하이브리드 게이밍\n09:12 소셜 게이밍 2.0\n12:30 마무리\n\n#게임트렌드 #2026게임 #AI게임`
  )
  const [tags, setTags] = useState(autoGeneratedTags)
  const [newTag, setNewTag] = useState("")
  const [visibility, setVisibility] = useState("public")
  const [scheduleUpload, setScheduleUpload] = useState(false)
  const [videoFile, setVideoFile] = useState<File | null>(null)
  const [isUploading, setIsUploading] = useState(false)
  const [uploadProgress, setUploadProgress] = useState(0)

  const handleRemoveTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove))
  }

  const handleAddTag = () => {
    if (newTag && !tags.includes(newTag)) {
      setTags([...tags, newTag])
      setNewTag("")
    }
  }

  const handleUpload = () => {
    setIsUploading(true)
    // Simulate upload progress
    const interval = setInterval(() => {
      setUploadProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval)
          return 100
        }
        return prev + 10
      })
    }, 500)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Video Upload Section */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <Film className="w-5 h-5 text-primary" />
            영상 파일
          </CardTitle>
        </CardHeader>
        <CardContent>
          {!videoFile ? (
            <label className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed border-border rounded-xl cursor-pointer hover:border-primary/50 hover:bg-muted/30 transition-colors">
              <div className="flex flex-col items-center justify-center pt-5 pb-6">
                <Upload className="w-10 h-10 text-muted-foreground mb-3" />
                <p className="mb-2 text-sm text-muted-foreground">
                  <span className="font-semibold text-foreground">클릭하여 업로드</span> 또는 드래그 앤 드롭
                </p>
                <p className="text-xs text-muted-foreground">MP4, MOV, AVI (최대 256GB)</p>
              </div>
              <input
                type="file"
                className="hidden"
                accept="video/*"
                onChange={(e) => setVideoFile(e.target.files?.[0] || null)}
              />
            </label>
          ) : (
            <div className="flex items-center gap-4 p-4 rounded-xl bg-muted/30 border border-border/50">
              <div className="w-16 h-16 rounded-lg bg-primary/20 flex items-center justify-center">
                <Film className="w-8 h-8 text-primary" />
              </div>
              <div className="flex-1">
                <p className="font-medium text-foreground">{videoFile.name}</p>
                <p className="text-sm text-muted-foreground">
                  {(videoFile.size / (1024 * 1024)).toFixed(2)} MB
                </p>
              </div>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => setVideoFile(null)}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Thumbnail Preview */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <ImageIcon className="w-5 h-5 text-primary" />
            썸네일 미리보기
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <div className="w-64 aspect-video rounded-lg bg-gradient-to-br from-primary via-chart-1 to-chart-5 flex items-center justify-center relative overflow-hidden">
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_30%,rgba(255,255,255,0.1),transparent_50%)]" />
              <div className="text-center relative z-10">
                <h3 className="text-lg font-bold text-white">2026년 게임 트렌드</h3>
                <p className="text-sm text-white/80">AI가 바꾸는 게임의 미래</p>
              </div>
            </div>
            <div className="flex-1 flex items-center">
              <div className="text-sm text-muted-foreground">
                <p className="flex items-center gap-2">
                  <Check className="w-4 h-4 text-accent" />
                  썸네일이 선택되었습니다
                </p>
                <p className="mt-2">이전 단계에서 생성한 썸네일이 자동으로 적용됩니다.</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Video Details */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            영상 정보
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="title">제목</Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="h-12"
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="description">설명</Label>
              <Badge variant="secondary" className="text-xs">
                <Sparkles className="w-3 h-3 mr-1" />
                AI 생성
              </Badge>
            </div>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="min-h-[200px] resize-none"
            />
          </div>
        </CardContent>
      </Card>

      {/* Tags */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <Tag className="w-5 h-5 text-primary" />
            태그
            <Badge variant="secondary" className="text-xs ml-2">
              <Sparkles className="w-3 h-3 mr-1" />
              자동 생성
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap gap-2">
            {tags.map((tag) => (
              <Badge
                key={tag}
                variant="secondary"
                className="px-3 py-1 text-sm cursor-pointer hover:bg-destructive/20 transition-colors"
                onClick={() => handleRemoveTag(tag)}
              >
                {tag}
                <X className="w-3 h-3 ml-1" />
              </Badge>
            ))}
          </div>
          <div className="flex gap-2">
            <Input
              placeholder="태그 추가..."
              value={newTag}
              onChange={(e) => setNewTag(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleAddTag()}
              className="flex-1"
            />
            <Button variant="outline" onClick={handleAddTag}>
              추가
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Upload Settings */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <Clock className="w-5 h-5 text-primary" />
            업로드 설정
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label>공개 설정</Label>
            <Select value={visibility} onValueChange={setVisibility}>
              <SelectTrigger className="h-12">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="public">
                  <div className="flex items-center gap-2">
                    <Globe className="w-4 h-4" />
                    공개
                  </div>
                </SelectItem>
                <SelectItem value="unlisted">
                  <div className="flex items-center gap-2">
                    <Users className="w-4 h-4" />
                    일부 공개
                  </div>
                </SelectItem>
                <SelectItem value="private">
                  <div className="flex items-center gap-2">
                    <Lock className="w-4 h-4" />
                    비공개
                  </div>
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-center justify-between p-4 rounded-lg bg-muted/30 border border-border/50">
            <div className="space-y-1">
              <Label htmlFor="schedule">예약 업로드</Label>
              <p className="text-sm text-muted-foreground">특정 시간에 자동으로 공개합니다</p>
            </div>
            <Switch
              id="schedule"
              checked={scheduleUpload}
              onCheckedChange={setScheduleUpload}
            />
          </div>

          {scheduleUpload && (
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="date">날짜</Label>
                <Input id="date" type="date" className="h-12" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="time">시간</Label>
                <Input id="time" type="time" className="h-12" />
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Upload Button */}
      <Card className="border-border/50 bg-card/50 backdrop-blur">
        <CardContent className="p-6">
          {!isUploading ? (
            <div className="flex flex-col items-center gap-4">
              <div className="flex items-start gap-3 p-4 rounded-lg bg-chart-4/10 border border-chart-4/20 w-full">
                <AlertCircle className="w-5 h-5 text-chart-4 flex-shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-medium text-foreground">업로드 전 확인사항</p>
                  <p className="text-muted-foreground mt-1">
                    영상 파일, 썸네일, 제목, 설명이 모두 준비되었는지 확인해주세요.
                    업로드 후에도 YouTube Studio에서 수정할 수 있습니다.
                  </p>
                </div>
              </div>
              <Button
                size="lg"
                className="w-full h-14 text-lg gap-3 bg-primary hover:bg-primary/90"
                onClick={handleUpload}
                disabled={!videoFile}
              >
                <Upload className="w-5 h-5" />
                YouTube에 업로드하기
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="font-medium">업로드 중...</span>
                <span className="text-primary font-bold">{uploadProgress}%</span>
              </div>
              <div className="w-full h-3 bg-muted rounded-full overflow-hidden">
                <div
                  className="h-full bg-primary transition-all duration-300"
                  style={{ width: `${uploadProgress}%` }}
                />
              </div>
              {uploadProgress === 100 && (
                <div className="flex items-center justify-center gap-2 text-accent">
                  <Check className="w-5 h-5" />
                  <span className="font-medium">업로드 완료!</span>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
