"""add competitor tables

Revision ID: b305e026e87d
Revises: 2026_01_26_0001
Create Date: 2026-01-29 15:50:10.521300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b305e026e87d'
down_revision: Union[str, None] = '2026_01_26_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=True),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('channel_title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption_meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selection_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['competitor_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitor_videos')
    op.drop_table('competitor_collections')
    # ### end Alembic commands ###
