"""add thumbnail tables

Revision ID: 20b699fe15b8
Revises: 2026_01_26_0001
Create Date: 2026-01-31 01:54:16.497211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b699fe15b8'
down_revision: Union[str, None] = '2026_01_26_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail_strategies',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name_kr', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thumbnail_generations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verified_script_id', sa.String(length=255), nullable=True),
    sa.Column('video_title', sa.String(length=200), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_video_url', sa.String(length=500), nullable=True),
    sa.Column('selected_keywords', sa.JSON(), nullable=False),
    sa.Column('selected_title_idx', sa.Integer(), nullable=False),
    sa.Column('selected_thumbnail_idx', sa.Integer(), nullable=False),
    sa.Column('title_sets', sa.JSON(), nullable=False),
    sa.Column('thumbnails', sa.JSON(), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_generations_created_at'), 'thumbnail_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_thumbnail_generations_user_id'), 'thumbnail_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_generations_user_id'), table_name='thumbnail_generations')
    op.drop_index(op.f('ix_thumbnail_generations_created_at'), table_name='thumbnail_generations')
    op.drop_table('thumbnail_generations')
    op.drop_table('thumbnail_strategies')
    # ### end Alembic commands ###
