"""add_script_pipeline_tables

Revision ID: 6a3cefa3f447
Revises: 9b7eaeca521a
Create Date: 2026-02-08 13:56:33.888522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a3cefa3f447'
down_revision: Union[str, None] = '9b7eaeca521a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('topic_title', sa.String(length=300), nullable=False),
    sa.Column('topic_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.channel_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_requests_status', 'topic_requests', ['status'], unique=False)
    op.create_index('ix_topic_requests_user_id', 'topic_requests', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_agent_name', 'agent_runs', ['agent_name'], unique=False)
    op.create_index('ix_agent_runs_topic_request_id', 'agent_runs', ['topic_request_id'], unique=False)
    op.create_table('article_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('query_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_sets_topic_request_id', 'article_sets', ['topic_request_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('selected_angle', sa.String(length=500), nullable=True),
    sa.Column('brief_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_briefs_topic_request_id', 'content_briefs', ['topic_request_id'], unique=False)
    op.create_table('fact_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_sets_topic_request_id', 'fact_sets', ['topic_request_id'], unique=False)
    op.create_table('insight_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('draft_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_packs_topic_request_id', 'insight_packs', ['topic_request_id'], unique=False)
    op.create_table('script_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_script_drafts_topic_request_id', 'script_drafts', ['topic_request_id'], unique=False)
    op.create_table('verified_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_request_id', sa.UUID(), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('final_script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('source_map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_request_id'], ['topic_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verified_scripts_topic_request_id', 'verified_scripts', ['topic_request_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_set_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_extraction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paywalled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_set_id'], ['article_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_set_id', 'url', name='uq_articles_set_url')
    )
    op.create_index('ix_articles_article_set_id', 'articles', ['article_set_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_set_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fact_set_id'], ['fact_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_fact_set_id', 'facts', ['fact_set_id'], unique=False)
    op.create_index(op.f('ix_facts_hash'), 'facts', ['hash'], unique=False)
    op.create_table('insight_sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_set_id', sa.UUID(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fact_set_id'], ['fact_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_draft_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('linked_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['script_draft_id'], ['script_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_script_claims_script_draft_id', 'script_claims', ['script_draft_id'], unique=False)
    op.create_table('visual_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_set_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fact_set_id'], ['fact_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('table_html', sa.Text(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_assets_article_id', 'article_assets', ['article_id'], unique=False)
    op.create_table('fact_dedupe_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_set_id', sa.UUID(), nullable=False),
    sa.Column('canonical_fact_id', sa.UUID(), nullable=False),
    sa.Column('merged_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_set_id'], ['fact_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('locator_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_evidences_article_id', 'fact_evidences', ['article_id'], unique=False)
    op.create_index('ix_fact_evidences_fact_id', 'fact_evidences', ['fact_id'], unique=False)
    op.create_table('script_source_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_draft_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['script_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_draft_id'], ['script_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_script_source_maps_claim_id', 'script_source_maps', ['claim_id'], unique=False)
    op.create_index('ix_script_source_maps_script_draft_id', 'script_source_maps', ['script_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_script_source_maps_script_draft_id', table_name='script_source_maps')
    op.drop_index('ix_script_source_maps_claim_id', table_name='script_source_maps')
    op.drop_table('script_source_maps')
    op.drop_index('ix_fact_evidences_fact_id', table_name='fact_evidences')
    op.drop_index('ix_fact_evidences_article_id', table_name='fact_evidences')
    op.drop_table('fact_evidences')
    op.drop_table('fact_dedupe_clusters')
    op.drop_index('ix_article_assets_article_id', table_name='article_assets')
    op.drop_table('article_assets')
    op.drop_table('visual_plans')
    op.drop_index('ix_script_claims_script_draft_id', table_name='script_claims')
    op.drop_table('script_claims')
    op.drop_table('insight_sentences')
    op.drop_index(op.f('ix_facts_hash'), table_name='facts')
    op.drop_index('ix_facts_fact_set_id', table_name='facts')
    op.drop_table('facts')
    op.drop_index('ix_articles_article_set_id', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_verified_scripts_topic_request_id', table_name='verified_scripts')
    op.drop_table('verified_scripts')
    op.drop_index('ix_script_drafts_topic_request_id', table_name='script_drafts')
    op.drop_table('script_drafts')
    op.drop_index('ix_insight_packs_topic_request_id', table_name='insight_packs')
    op.drop_table('insight_packs')
    op.drop_index('ix_fact_sets_topic_request_id', table_name='fact_sets')
    op.drop_table('fact_sets')
    op.drop_index('ix_content_briefs_topic_request_id', table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index('ix_article_sets_topic_request_id', table_name='article_sets')
    op.drop_table('article_sets')
    op.drop_index('ix_agent_runs_topic_request_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_name', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_topic_requests_user_id', table_name='topic_requests')
    op.drop_index('ix_topic_requests_status', table_name='topic_requests')
    op.drop_table('topic_requests')
    # ### end Alembic commands ###
