"""add video_captions table

Revision ID: b50621fad5ac
Revises: b305e026e87d
Create Date: 2026-01-29 16:16:04.648189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50621fad5ac'
down_revision: Union[str, None] = 'b305e026e87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_captions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_video_id', sa.UUID(), nullable=False),
    sa.Column('segments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['competitor_video_id'], ['competitor_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_captions')
    # ### end Alembic commands ###
