"""add script_chunks and image_refs to thumbnail_generations

Revision ID: f3ada8968c4b
Revises: 20b699fe15b8
Create Date: 2026-01-31 02:01:43.790276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ada8968c4b'
down_revision: Union[str, None] = '20b699fe15b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnail_generations', sa.Column('script_summary', sa.String(length=500), nullable=True))
    op.add_column('thumbnail_generations', sa.Column('script_chunks', sa.JSON(), nullable=False))
    op.add_column('thumbnail_generations', sa.Column('image_refs', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thumbnail_generations', 'image_refs')
    op.drop_column('thumbnail_generations', 'script_chunks')
    op.drop_column('thumbnail_generations', 'script_summary')
    # ### end Alembic commands ###
